configs:
  params:
    server.insecure: "true"  # modern way of disabling ssl redirection
  cm:
    url: https://argocd.app.fahim-dev.com
    application.instanceLabelKey: argocd.argoproj.io/instance
server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: argocd.app.fahim-dev.com
    paths: 
      - /
    pathType: Prefix
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.app.fahim-dev.com
controller:
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

applicationSet:
  replicas: 1