global:
  domain: argocd.app.fahim-dev.com
configs:
  params:
    server.insecure: "true"
  cm:
    url: https://argocd.app.fahim-dev.com
    application.instanceLabelKey: argocd.argoproj.io/instance
server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: argocd.app.fahim-dev.com
    path: /
    pathType: Prefix
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
controller:
  replicas: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

applicationSet:
  replicas: 1