deployment:
  replicas: 1
resource:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
ports:
  web:
    redirectTo:
      port: websecure
    websecure:
      tls:
        enabled: true
metrics:
  prometheus:
    entrypoint: metrics
    addRouterLabels: true
ingressClass:
  enabled: true
  isDefaultClass: true


