apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Fah7m/PodInfo-EKS-deployment
    targetRevision: main
    path: argocd/base/podinfo-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
